### ISSUE TITLE
Remove threshold from token

### ISSUE THREAD

**Issue by xn3cr0nx** [Poseidon-DAO/contracts#1]
### Context

We cannot relate any reward mechanism to the token in order to ensure it is not identified as a security. Check in the smart contract and remove if any.

### Acceptance Criteria

- No reward mechanism for token owners is implemented in the smart contract

**Comment by mauro-tommasi** [comment]
I deleted the previous branch and did a new one due to wrong commits about .env. I followed all instructions and I'm asking to review the code.
